from easygrade.eval.run_eval import evaluate, report
from easygrade.pipeline.grader import grade as g

from .test_eval import write
from .test_grade import NOTEBOOK, RUBRIC, TRANSCRIPT, FakeClient, good_output


def run_with_ai(ai_usage, **kw):
    out = good_output()
    out["ai_usage"] = ai_usage
    client = FakeClient(out)
    return g.grade(client, "team-001", RUBRIC, TRANSCRIPT, NOTEBOOK, **kw), client


def codes(s):
    return [f.code for f in s.flags]


def test_review_with_verified_evidence_is_kept_and_flagged():
    s, _ = run_with_ai({"status": "review", "note": "Spoken R squared differs from the notebook.",
                        "evidence": [{"source": "transcript", "ref": "s3", "quote": "R squared on the test set was 0.71"}]})
    assert s.ai_usage.status == "review"
    assert s.ai_usage.evidence[0].verified
    assert "AI_USAGE_REVIEW" in codes(s)


def test_review_with_made_up_evidence_is_dropped():
    s, _ = run_with_ai({"status": "review", "note": "x",
                        "evidence": [{"source": "notebook", "ref": 1, "quote": "generated by ChatGPT"}]})
    assert s.ai_usage.status == "no_concern"
    assert "AI_USAGE_REVIEW" not in codes(s)


def test_review_without_evidence_is_dropped():
    s, _ = run_with_ai({"status": "review", "note": "Writing seems too polished.", "evidence": []})
    assert s.ai_usage.status == "no_concern" and "AI_USAGE_REVIEW" not in codes(s)


def test_every_review_flag_has_verified_evidence():
    cases = [
        {"status": "review", "evidence": [{"source": "notebook", "ref": 1, "quote": "dropna"}]},
        {"status": "review", "evidence": [{"source": "notebook", "ref": 2, "quote": "dropna"}]},  # wrong cell
        {"status": "review", "evidence": []},
        {"status": "no_concern", "evidence": []},
    ]
    for case in cases:
        s, _ = run_with_ai(case)
        if s.ai_usage.status == "review":
            assert any(ev.verified for ev in s.ai_usage.evidence)


def test_ai_evidence_counts_in_quote_totals():
    s, _ = run_with_ai({"status": "review", "evidence": [{"source": "notebook", "ref": 1, "quote": "dropna"}]})
    assert s.validation.quotes_checked == 3 and s.validation.quotes_verified == 3


def test_policy_goes_in_system_prompt_and_defaults_to_no_disclosure_check():
    _, client = run_with_ai({"status": "no_concern"})
    assert "Do not raise a missing disclosure" in client.calls[0]["system"]
    _, client = run_with_ai({"status": "no_concern"}, ai_policy="Students must disclose any AI tool use in the header.")
    assert "must disclose" in client.calls[0]["system"]


def test_system_prompt_says_style_is_never_evidence():
    _, client = run_with_ai({"status": "no_concern"})
    assert "non-native English are never" in client.calls[0]["system"]


def test_review_counts_by_group(tmp_path):
    key = {"level_keys": ["excellent", "good", "needs_work"], "teams": {
        "t1": {"group": "native", "planned_levels": {}},
        "t2": {"group": "native", "planned_levels": {}},
        "t3": {"group": "non_native_english", "planned_levels": {}},
        "t4": {"group": "non_native_english", "planned_levels": {}},
    }}
    for t, status in [("t1", "no_concern"), ("t2", "no_concern"), ("t3", "review"), ("t4", "review")]:
        write(tmp_path / t / "suggestion.json", {"prompt_version": "v", "sections": [], "ai_usage": {"status": status}})
    r = evaluate(tmp_path, key)
    assert r.review_by_group == {"native": [0, 2], "non_native_english": [2, 2]}
    assert "non_native_english: 2/2 (100%)" in report(r)
